presets_usd = {
    "Default-usd": {
        "filepath": "",
        "selected_objects_only": False,
        "collection": "",
        "export_animation": False,
        "incremental_frames": 0,
        "export_hair": False,
        "export_uvmaps": True,
        "rename_uvmaps": True,
        "export_normals": True,
        "export_materials": True,
        "export_subdivision": "BEST_MATCH",
        "export_armatures": True,
        "only_deform_bones": False,
        "export_shapekeys": True,
        "use_instancing": False,
        "evaluation_mode": "RENDER",
        "generate_preview_surface": True,
        "convert_orientation": False,
        "export_global_forward_selection": "NEGATIVE_Z",
        "export_global_up_selection": "Y",
        "export_textures_mode": "NEW",
        "overwrite_textures": False,
        "relative_paths": True,
        "xform_op_mode": "TRS",
        "root_prim_path": "/root",
        "export_custom_properties": True,
        "custom_properties_namespace": "userProperties",
        "author_blender_name": True,
        "convert_world_material": True,
        "export_meshes": True,
        "export_lights": True,
        "export_cameras": True,
        "export_curves": True,
        "export_points": True,
        "export_volumes": True,
        "triangulate_meshes": False,
        "quad_method": "SHORTEST_DIAGONAL",
        "ngon_method": "BEAUTY",
        "merge_parent_xform": False,
        # Kept last: newer USD-exporter options not confirmed present on every
        # supported Blender version (live-verified on 5.2 only). Blender's native
        # preset loader (script.execute_preset) execs this file top to bottom and
        # aborts on the first unknown property, so keeping these at the end means
        # every earlier property still gets applied on older Blender versions
        # instead of being skipped.
        "export_mesh_colors": True,
        "generate_materialx_network": False,
        "allow_unicode": True,
        "usdz_downscale_size": "KEEP",
        "usdz_downscale_custom_size": 128,
        "convert_scene_units": "METERS",
        "meters_per_unit": 1.0,
        "accessibility_label": "",
        "accessibility_description": "",
    },
    "Default-animation-usd": {
        "filepath": "",
        "selected_objects_only": False,
        "collection": "",
        "export_animation": True,
        "incremental_frames": 0,
        "export_hair": False,
        "export_uvmaps": True,
        "rename_uvmaps": True,
        "export_normals": True,
        "export_materials": True,
        "export_subdivision": "BEST_MATCH",
        "export_armatures": True,
        "only_deform_bones": False,
        "export_shapekeys": True,
        "use_instancing": False,
        "evaluation_mode": "RENDER",
        "generate_preview_surface": True,
        "convert_orientation": False,
        "export_global_forward_selection": "NEGATIVE_Z",
        "export_global_up_selection": "Y",
        "export_textures_mode": "NEW",
        "overwrite_textures": False,
        "relative_paths": True,
        "xform_op_mode": "TRS",
        "root_prim_path": "/root",
        "export_custom_properties": True,
        "custom_properties_namespace": "userProperties",
        "author_blender_name": True,
        "convert_world_material": True,
        "export_meshes": True,
        "export_lights": True,
        "export_cameras": True,
        "export_curves": True,
        "export_points": True,
        "export_volumes": True,
        "triangulate_meshes": False,
        "quad_method": "SHORTEST_DIAGONAL",
        "ngon_method": "BEAUTY",
        "merge_parent_xform": False,
        # Kept last: newer USD-exporter options not confirmed present on every
        # supported Blender version (live-verified on 5.2 only). Blender's native
        # preset loader (script.execute_preset) execs this file top to bottom and
        # aborts on the first unknown property, so keeping these at the end means
        # every earlier property still gets applied on older Blender versions
        # instead of being skipped.
        "export_mesh_colors": True,
        "generate_materialx_network": False,
        "allow_unicode": True,
        "usdz_downscale_size": "KEEP",
        "usdz_downscale_custom_size": 128,
        "convert_scene_units": "METERS",
        "meters_per_unit": 1.0,
        "accessibility_label": "",
        "accessibility_description": "",
    },
}
