import os

from ..presets_export import get_fbx_presets_folder
from ..presets_export import get_gltf_presets_folder

presets_simple_exporter = {
    "UE-default": {
        "export_format": "FBX",
        "export_folder_mode": "RELATIVE",
        "folder_path_absolute": "C:\\tmp\\",
        "folder_path_relative": "//export/",
        "folder_path_search": "work",
        "folder_path_replace": "source",
        "filename_prefix": "",
        "filename_suffix": "",
        "filename_blend_prefix": False,
        "set_export_path": True,
        "simple_export_preset_file_fbx": os.path.join(get_fbx_presets_folder(), "UE-fbx.py"),
        "assign_preset": True,
        "collection_prefix": "SM",
        "collection_suffix": "",
        "collection_blend_prefix": False,
        "use_root_object": True,
        "collection_instance_offset": False,
        "collection_color": "COLOR_02",
        "parent_collection": "Export",
    },
    "Unity-default": {
        "export_format": "FBX",
        "export_folder_mode": "RELATIVE",
        "folder_path_absolute": "C:\\tmp\\",
        "folder_path_relative": "//export/",
        "folder_path_search": "work",
        "folder_path_replace": "source",
        "filename_prefix": "",
        "filename_suffix": "",
        "filename_blend_prefix": False,
        "set_export_path": True,
        "simple_export_preset_file_fbx": os.path.join(get_fbx_presets_folder(), "Unity-fbx.py"),
        "assign_preset": True,
        "collection_prefix": "",
        "collection_suffix": "",
        "collection_blend_prefix": False,
        "use_root_object": True,
        "collection_instance_offset": False,
        "collection_color": "COLOR_06",
        "parent_collection": "Export",
    },
    "Godot-default": {
        "export_format": "GLTF",
        "export_folder_mode": "RELATIVE",
        "folder_path_absolute": "C:\\tmp\\",
        "folder_path_relative": "//export/",
        "folder_path_search": "work",
        "folder_path_replace": "source",
        "filename_prefix": "",
        "filename_suffix": "",
        "filename_blend_prefix": False,
        "set_export_path": True,
        "simple_export_preset_file_gltf": os.path.join(get_gltf_presets_folder(), "Godot-gltf.py"),
        "assign_preset": True,
        "collection_prefix": "",
        "collection_suffix": "",
        "collection_blend_prefix": False,
        "use_root_object": True,
        "collection_instance_offset": False,
        "collection_color": "COLOR_05",
        "parent_collection": "Export",
    },
    "Lowpoly-default": {
        "export_format": "FBX",
        "export_folder_mode": "RELATIVE",
        "folder_path_absolute": "C:\\tmp\\",
        "folder_path_relative": "//bake/",
        "folder_path_search": "work",
        "folder_path_replace": "source",
        "filename_prefix": "",
        "filename_suffix": "",
        "filename_blend_prefix": False,
        "set_export_path": True,
        "simple_export_preset_file_fbx": os.path.join(get_fbx_presets_folder(), "Lowpoly-fbx.py"),
        "assign_preset": True,
        "collection_prefix": "",
        "collection_suffix": "low",
        "collection_blend_prefix": False,
        "collection_instance_offset": False,
        "collection_color": "COLOR_04",
        "use_root_object": True,
        "parent_collection": "Low",
    },

    "Highpoly-default": {
        "export_format": "FBX",
        "export_folder_mode": "RELATIVE",
        "folder_path_absolute": "C:\\tmp\\",
        "folder_path_relative": "//bake/",
        "folder_path_search": "work",
        "folder_path_replace": "source",
        "filename_prefix": "",
        "filename_suffix": "",
        "filename_blend_prefix": False,
        "set_export_path": True,
        "simple_export_preset_file_fbx": os.path.join(get_fbx_presets_folder(), "Highpoly-fbx.py"),
        "assign_preset": True,
        "collection_prefix": "",
        "collection_suffix": "high",
        "collection_blend_prefix": False,
        "collection_instance_offset": False,
        "collection_color": "COLOR_03",
        "use_root_object": True,
        "parent_collection": "High",
    },
    # "Northlight-default": {
    #     "export_format": "FBX",
    #     "export_folder_mode": "MIRROR",
    #     "folder_path_absolute": "C:\\tmp\\",
    #     "folder_path_relative": "//",
    #     "folder_path_search": "workdata",
    #     "folder_path_replace": "sourcedata",
    #     "filename_prefix": "",
    #     "filename_suffix": "",
    #     "filename_blend_prefix": False,
    #     "set_export_path": True,
    #     "simple_export_preset_file_fbx": os.path.join(get_fbx_presets_folder(), "Northlight-fbx.py"),
    #     "assign_preset": True,
    #     "collection_prefix": "",
    #     "collection_suffix": "",
    #     "collection_blend_prefix": False,
    #     "use_root_object": True,
    #     "collection_instance_offset": False,
    #     "collection_color": "COLOR_01",
    #     "parent_collection": "Export",
    # },
}
