presets_fbx = {
    "UE-fbx": {
        "filepath": "",
        "use_selection": False,
        "use_visible": False,
        "use_active_collection": True,
        "collection": "",
        "global_scale": 1.0,
        "apply_unit_scale": True,
        "apply_scale_options": "FBX_SCALE_UNITS",
        "use_space_transform": False,
        "bake_space_transform": False,
        "object_types": {'EMPTY', 'MESH', 'OTHER', 'ARMATURE'},
        "use_mesh_modifiers": True,
        "use_mesh_modifiers_render": True,
        "mesh_smooth_type": "OFF",
        "colors_type": "SRGB",
        "prioritize_active_color": False,
        "use_subsurf": False,
        "use_mesh_edges": False,
        "use_tspace": False,
        "use_triangles": False,
        "use_custom_props": True,
        "add_leaf_bones": False,
        "primary_bone_axis": "Y",
        "secondary_bone_axis": "X",
        "use_armature_deform_only": False,
        "armature_nodetype": "NULL",
        "bake_anim": False,
        "bake_anim_use_all_bones": True,
        "bake_anim_use_nla_strips": True,
        "bake_anim_use_all_actions": False,
        "bake_anim_force_startend_keying": True,
        "bake_anim_step": 1.0,
        "bake_anim_simplify_factor": 1.0,
        "path_mode": "STRIP",
        "embed_textures": False,
        "batch_mode": "OFF",
        "use_batch_own_dir": True,
        "axis_forward": "X",
        "axis_up": "Z",
    },
    "Unity-fbx": {
        "filepath": "",
        "use_selection": False,
        "use_visible": False,
        "use_active_collection": True,
        "collection": "",
        "global_scale": 1.0,
        "apply_unit_scale": True,
        "apply_scale_options": "FBX_SCALE_UNITS",
        "axis_forward": "-Y",
        "axis_up": "Z",
        "use_space_transform": False,
        "bake_space_transform": False,
        "object_types": {'EMPTY', 'MESH', 'OTHER', 'ARMATURE'},
        "use_mesh_modifiers": True,
        "use_mesh_modifiers_render": True,
        "mesh_smooth_type": "OFF",
        "colors_type": "SRGB",
        "prioritize_active_color": False,
        "use_subsurf": False,
        "use_mesh_edges": False,
        "use_tspace": False,
        "use_triangles": False,
        "use_custom_props": True,
        "add_leaf_bones": True,
        "primary_bone_axis": "Y",
        "secondary_bone_axis": "X",
        "use_armature_deform_only": True,
        "armature_nodetype": "NULL",
        "bake_anim": False,
        "bake_anim_use_all_bones": True,
        "bake_anim_use_nla_strips": True,
        "bake_anim_use_all_actions": False,
        "bake_anim_force_startend_keying": True,
        "bake_anim_step": 1.0,
        "bake_anim_simplify_factor": 1.0,
        "path_mode": "STRIP",
        "embed_textures": False,
        "batch_mode": "OFF",
        "use_batch_own_dir": True,
    },
    "Lowpoly-fbx": {
        "filepath": "",
        "use_selection": False,
        "use_visible": False,
        "use_active_collection": True,
        "collection": "",
        "global_scale": 1.0,
        "apply_unit_scale": True,
        "apply_scale_options": "FBX_SCALE_ALL",
        "use_space_transform": False,
        "bake_space_transform": False,
        "object_types": {'EMPTY', 'CAMERA', 'LIGHT', 'ARMATURE', 'MESH', 'OTHER'},
        "use_mesh_modifiers": True,
        "use_mesh_modifiers_render": True,
        "mesh_smooth_type": "OFF",
        "colors_type": "SRGB",
        "prioritize_active_color": False,
        "use_subsurf": False,
        "use_mesh_edges": False,
        "use_tspace": True,
        "use_triangles": False,
        "use_custom_props": True,
        "add_leaf_bones": False,
        "primary_bone_axis": "-Z",
        "secondary_bone_axis": "X",
        "use_armature_deform_only": False,
        "armature_nodetype": "NULL",
        "bake_anim": False,
        "bake_anim_use_all_bones": True,
        "bake_anim_use_nla_strips": True,
        "bake_anim_use_all_actions": True,
        "bake_anim_force_startend_keying": True,
        "bake_anim_step": 1.0,
        "bake_anim_simplify_factor": 1.0,
        "path_mode": "STRIP",
        "embed_textures": False,
        "batch_mode": "OFF",
        "use_batch_own_dir": True,
        "axis_forward": "-Y",
        "axis_up": "Z",
    },
    "Highpoly-fbx": {
        "filepath": "",
        "use_selection": False,
        "use_visible": False,
        "use_active_collection": True,
        "collection": "",
        "global_scale": 1.0,
        "apply_unit_scale": True,
        "apply_scale_options": "FBX_SCALE_UNITS",
        "use_space_transform": False,
        "bake_space_transform": False,
        "object_types": {'EMPTY', 'MESH', 'OTHER'},
        "use_mesh_modifiers": True,
        "use_mesh_modifiers_render": True,
        "mesh_smooth_type": "OFF",
        "colors_type": "SRGB",
        "prioritize_active_color": False,
        "use_subsurf": False,
        "use_mesh_edges": False,
        "use_tspace": True,
        "use_triangles": False,
        "use_custom_props": True,
        "add_leaf_bones": False,
        "primary_bone_axis": "-Z",
        "secondary_bone_axis": "X",
        "use_armature_deform_only": False,
        "armature_nodetype": "NULL",
        "bake_anim": False,
        "bake_anim_use_all_bones": True,
        "bake_anim_use_nla_strips": True,
        "bake_anim_use_all_actions": True,
        "bake_anim_force_startend_keying": True,
        "bake_anim_step": 1.0,
        "bake_anim_simplify_factor": 1.0,
        "path_mode": "STRIP",
        "embed_textures": False,
        "batch_mode": "OFF",
        "use_batch_own_dir": True,
        "axis_forward": "-Y",
        "axis_up": "Z",
    },
    # "Northlight-fbx": {
    #     "filepath": "",
    #     "use_selection": False,
    #     "use_visible": False,
    #     "use_active_collection": True,
    #     "collection": "",
    #     "global_scale": 1.0,
    #     "apply_unit_scale": True,
    #     "apply_scale_options": "FBX_SCALE_ALL",
    #     "use_space_transform": True,
    #     "bake_space_transform": False,
    #     "object_types": {'EMPTY', 'CAMERA', 'LIGHT', 'ARMATURE', 'MESH', 'OTHER'},
    #     "use_mesh_modifiers": True,
    #     "use_mesh_modifiers_render": True,
    #     "mesh_smooth_type": "OFF",
    #     "colors_type": "SRGB",
    #     "prioritize_active_color": False,
    #     "use_subsurf": False,
    #     "use_mesh_edges": False,
    #     "use_tspace": True,
    #     "use_triangles": False,
    #     "use_custom_props": True,
    #     "add_leaf_bones": False,
    #     "primary_bone_axis": "-Z",
    #     "secondary_bone_axis": "X",
    #     "use_armature_deform_only": False,
    #     "armature_nodetype": "NULL",
    #     "bake_anim": False,
    #     "bake_anim_use_all_bones": True,
    #     "bake_anim_use_nla_strips": True,
    #     "bake_anim_use_all_actions": True,
    #     "bake_anim_force_startend_keying": True,
    #     "bake_anim_step": 1.0,
    #     "bake_anim_simplify_factor": 1.0,
    #     "path_mode": "STRIP",
    #     "embed_textures": False,
    #     "batch_mode": "OFF",
    #     "use_batch_own_dir": True,
    #     "axis_forward": "-Z",
    #     "axis_up": "Y",
    # }
}
